# inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/**/*'
    - 'config/initializers/devise.rb'

Metrics/AbcSize:
  Max: 20
  Exclude:
   - 'db/**/*'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'db/**/*'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - '**/*.rake'
    - 'config/routes.rb'

Style/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Rails/Output:
  Exclude:
    - 'lib/shapefiles.rb'