language: ruby

rvm:
  - 2.3.3

sudo: false

cache: bundler

bundler_args: --without development --retry=3 --jobs=3

services:
  - postgresql

before_install:
  - gem update --system
  - gem install bundler
  - gem update bundler

before_script:
  - psql -c 'create database phonerep_test;' -U postgres
  - psql -U postgres -c 'create extension postgis;'

notifications:
  email:
    on_success: change
    on_failure: always
