language: ruby

rvm:
  - 2.3.3

sudo: false

cache: bundler

bundler_args: --without development --retry=3 --jobs=3

before_install:
  - gem update --system
  - gem install bundler
  - gem update bundler

notifications:
  email:
    on_success: never
    on_failure: always
