language: ruby

rvm:
  - 2.4.1
  - ruby-head

sudo: false

cache: bundler

bundler_args: --without development --retry=3 --jobs=3

services:
  - postgresql

addons:
  postgresql: 9.6
  apt:
    packages:
    - postgresql-9.6-postgis-2.3

before_install:
  - gem update --system
  - gem install bundler
  - gem update bundler

before_script:
  - psql -c 'create database phonerep_test;' -U postgres
  - psql -U postgres -c 'create extension postgis;'

matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    on_success: change
    on_failure: always
